### ISSUE TITLE
bing阅读的一点疑问

### ISSUE THREAD

**Issue by jaychoubaby** [MCdasheng/QuantumultX#3]
我的理解是这个bing阅读是要手动获取每个文章的id？但是task执行的时候这些id因为都阅读过了，所以不会给积分了提示报错：
`{
    "response": {
        "balance": 76,
        "activity": {
            "id": "a600bc89b22e1b0813fbbe2747850fcffbf1abe7a0217b2add3bec5c9655c15e",
            "id_old": null,
            "m": "cn",
            "t": "2023-08-24T02:07:53.068374+00:00",
            "type": 101,
            "p": 0,
            "q": 1,
            "a": {
                "offerid": "ENUS_readarticle3_30points"
            },
            "rbTxEntry": null
        },
        "info": null,
        "isDuplicate": true,
        "notifications": null,
        "isExpiredTrialUser": false
    },
    "correlationId": "286142795f464e9ead5daa2ec92d0f5e",
    "code": 0
}`

意思是我第二天执行可以直接拿上次收集到的id执行就可以重新获取积分？

**Comment by MCdasheng** [comment]
> 我的理解是这个bing阅读是要手动获取每个文章的id？但是task执行的时候这些id因为都阅读过了，所以不会给积分了提示报错： `{ "response": { "balance": 76, "activity": { "id": "a600bc89b22e1b0813fbbe2747850fcffbf1abe7a0217b2add3bec5c9655c15e", "id_old": null, "m": "cn", "t": "2023-08-24T02:07:53.068374+00:00", "type": 101, "p": 0, "q": 1, "a": { "offerid": "ENUS_readarticle3_30points" }, "rbTxEntry": null }, "info": null, "isDuplicate": true, "notifications": null, "isExpiredTrialUser": false }, "correlationId": "286142795f464e9ead5daa2ec92d0f5e", "code": 0 }`
> 
> 意思是我第二天执行可以直接拿上次收集到的id执行就可以重新获取积分？

id是每天更新的，不可以跨天使用。
这样用一个账号手动观看，会自动记录id，用于其他账号做这个任务
如果只有一个账号，意义不大
这个json中 p=0 就是没有获得积分
如果下次没有回复，可以在https://t.me/mcdasheng6888 找我～

**Comment by jaychoubaby** [comment]
明白了  感谢解答
